name: "Publish release with notes"
description: "GitHub Action to publish a release with release notes"
inputs:
  token:
    description: "The GitHub token"
    required: true
    default: ${{ github.token }}
  id:
    description: "Release identifier"
    required: true
  version:
    description: "Release version"
    required: true
  notes:
    description: "Release notes file path"
    required: true
runs:
  using: "node20"
  main: "index.js"
